"""The multi-Book Write ID3 pipeline — v0.6.3 focused MP3 plan, Phase 7.

``mp3_tools/mp3_processing.py`` runs one frozen Phase 5 ``RunPlan`` for the
Write ID3 Tags operation: every track becomes a **new clean staged copy** with the
frozen signed Time applied, then carries exactly the whitelisted ID3 frames the
plan intends (Title, Artist / Album Artist / Album when populated, Track Number
when Auto-number is on, one front cover from the Phase 6 artwork service), and
a Book is published only when every track staged and validated. A failed Book
publishes nothing; its successful pieces stay in private staging for the later
exact failed-item retry; later Books still run.

Real media, deliberately: sources are one-second tones generated by the pinned
FFmpeg under ``tmp_path`` and tagged with junk frames by mutagen. Nothing here
opens a controller, a thread, a widget or Combine.
"""

from __future__ import annotations

import ast
import hashlib
from pathlib import Path, PurePath

import pytest
from PIL import Image
from mutagen.id3 import APIC, COMM, ID3, TALB, TCOM, TCON, TIT2, TPE1, TRCK, TXXX, TYER

from shared import book_workspace, ffmpeg_utils, output_paths
from shared import subprocess_utils as sp
from shared.book_workspace import BookJob, SharedMetadata, WorkspaceSnapshot
from shared.importing import (
    IdFactory,
    ImportOptions,
    ImportedFile,
    ImportedFileSnapshot,
    ImportRoot,
    Revision,
)
from shared.job_control import FailureRecord, JobState, RunResult

from mp3_tools import mp3_artwork as art
from mp3_tools import mp3_plan as mp
from mp3_tools import mp3_processing as proc
from mp3_tools import mp3_workflow as wf
from mp3_tools.mp3_processing import BookReport, WriteId3Report

from test_importing import make_config

pytestmark = pytest.mark.skipif(
    not ffmpeg_utils.have_ffmpeg(), reason="ffmpeg/ffprobe not available in this environment")

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIVERSAL = REPO_ROOT / "scripts" / "Universal"
MODULE = UNIVERSAL / "mp3_tools" / "mp3_processing.py"

_IDS = IdFactory("w-")

#: Every user-facing frame the pipeline may write, and no other.
WHITELIST = {"TIT2", "TPE1", "TPE2", "TALB", "TRCK", "APIC"}


# --------------------------------------------------------------------------- #
# Fixtures: real one-second tones, junk-tagged, never repository media
# --------------------------------------------------------------------------- #


def tone(path: Path, seconds: float = 1.0, freq: int = 440) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    sp.run([ffmpeg_utils.ffmpeg_cmd(), "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", f"sine=frequency={freq}:duration={seconds}",
            "-ac", "2", "-ar", "44100", "-c:a", "libmp3lame", "-b:a", "64k", str(path)],
           check=True)
    return path


def junk_tag(path: Path, *, title="Old Title", artist="Old Artist", album="Old Album",
             with_art=True) -> Path:
    tags = ID3()
    tags.add(TIT2(encoding=3, text=[title]))
    tags.add(TPE1(encoding=3, text=[artist]))
    tags.add(TALB(encoding=3, text=[album]))
    tags.add(TRCK(encoding=3, text=["77"]))
    tags.add(TYER(encoding=3, text=["1999"]))
    tags.add(TCON(encoding=3, text=["Speech"]))
    tags.add(TCOM(encoding=3, text=["Old Composer"]))
    tags.add(COMM(encoding=3, lang="eng", desc="", text=["old comment"]))
    tags.add(TXXX(encoding=3, desc="custom", text=["x"]))
    if with_art:
        tags.add(APIC(encoding=3, mime="image/jpeg", type=3, desc="old", data=b"old-art"))
    tags.save(path, v2_version=3)
    return path


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def duration(path: Path) -> float:
    value = proc.ffprobe_duration_seconds(path)
    assert value is not None, path
    return value


def frames(path: Path) -> dict[str, object]:
    try:
        tags = ID3(path)
    except Exception:
        return {}
    return {key.split(":")[0]: frame for key, frame in tags.items()}


def texts(path: Path) -> dict[str, str]:
    return {key: "/".join(str(t) for t in frame.text)
            for key, frame in frames(path).items() if hasattr(frame, "text")}


def png(path: Path, size=(24, 16)) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (200, 30, 30)).save(path, format="PNG")
    return path


def jpg(path: Path, size=(32, 20)) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (30, 200, 30)).save(path, format="JPEG", quality=90)
    return path


@pytest.fixture
def sources(tmp_path: Path) -> Path:
    root = tmp_path / "Sources"
    root.mkdir()
    return root


@pytest.fixture
def reserve(tmp_path: Path):
    counter = {"n": 0}

    def make(tool_key="mp3_tool", **_kw):
        counter["n"] += 1
        directory = tmp_path / "Outputs" / f"MP3-Tool-{counter['n']}"
        directory.mkdir(parents=True)
        return output_paths.RunReservation(
            tool_key=tool_key, base_directory=tmp_path / "Outputs",
            tool_directory=tmp_path / "Outputs", run_directory=directory,
            run_number=counter["n"])

    make.calls = counter  # type: ignore[attr-defined]
    return make


def imported(sources: Path, folder: str, name: str, *, seconds=1.0, freq=440,
             junk=True, with_art=True, title="Old Title") -> ImportedFile:
    path = tone(sources / folder / name, seconds=seconds, freq=freq)
    if junk:
        junk_tag(path, with_art=with_art, title=title)
    occurrence = _IDS.next_id("occurrence")
    return ImportedFile(occurrence, path, ImportRoot("r", sources, 0),
                        PurePath(folder) / name, "mp3", f"id-{occurrence}")


def book(files, **configuration) -> BookJob:
    return BookJob(book_id=book_workspace.new_book_id(_IDS), configuration=configuration,
                   files=ImportedFileSnapshot(Revision(1), tuple(files)))


def workspace(*books: BookJob, shared: SharedMetadata | None = None) -> WorkspaceSnapshot:
    return WorkspaceSnapshot(
        books=books, current_book_id=books[0].book_id,
        shared=wf.new_shared_metadata() if shared is None else shared)


def observe(*books: BookJob) -> wf.ObservationStore:
    store = wf.ObservationStore()
    for entry in books:
        store = store.with_observations(wf.observe_files(entry.files.files))
    return store


def plan(space, store, reserve, **kwargs) -> mp.RunPlan:
    return mp.plan_run(
        space, store, operation=mp.MP3Operation.WRITE_ID3, reservation=reserve(),
        catalog=wf.MP3_CATALOG, import_options=ImportOptions.for_catalog(wf.MP3_CATALOG),
        effective_config=make_config(), id_factory=_IDS, **kwargs)


def one_book_plan(sources, reserve, names=("01 One.mp3",), title="Old Title", **configuration):
    files = [imported(sources, "Book", name, title=title) for name in names]
    entry = book(files, **configuration)
    return plan(workspace(entry), observe(entry), reserve), entry


# --------------------------------------------------------------------------- #
# Zero, positive and negative Time on real audio
# --------------------------------------------------------------------------- #


def test_zero_time_still_creates_a_distinct_clean_output(sources, reserve):
    made, entry = one_book_plan(sources, reserve)
    source = entry.files.files[0].path
    before = sha(source)
    report = proc.write_id3_run(made)
    assert isinstance(report, WriteId3Report)
    track = made.books[0].tracks[0]
    assert track.published.is_file()
    assert track.published != source
    assert sha(source) == before, "the source is read-only"
    assert sha(track.published) != before, "a new clean file, not a copy of the bytes"
    assert abs(duration(track.published) - duration(source)) < 0.15
    assert report.books[0].succeeded


def test_positive_time_appends_to_the_end(sources, reserve):
    made, entry = one_book_plan(sources, reserve, time_delta="1.5")
    source = entry.files.files[0].path
    proc.write_id3_run(made)
    out = made.books[0].tracks[0].published
    assert abs(duration(out) - (duration(source) + 1.5)) < 0.2
    assert made.books[0].time_delta == 1.5


def test_negative_time_trims_from_the_end(sources, reserve):
    files = [imported(sources, "Book", "01.mp3", seconds=3.0)]
    entry = book(files, time_delta="-1")
    made = plan(workspace(entry), observe(entry), reserve)
    proc.write_id3_run(made)
    out = made.books[0].tracks[0].published
    assert abs(duration(out) - (duration(files[0].path) - 1.0)) < 0.2


def test_an_excessive_trim_fails_safely_with_the_real_occurrence(sources, reserve):
    files = [imported(sources, "Book", "01.mp3", seconds=1.0),
             imported(sources, "Book", "02.mp3", seconds=1.0)]
    entry = book(files, time_delta="-5")
    made = plan(workspace(entry), observe(entry), reserve)
    report = proc.write_id3_run(made)
    result = report.books[0]
    assert result.succeeded is False
    assert not made.books[0].published_dir.exists(), "no partial Book is visible"
    assert not any(t.published.exists() for t in made.books[0].tracks)
    failures = result.result.failures.records
    assert {f.item_id for f in failures} == {f.occurrence_id for f in files}
    for record in failures:
        assert isinstance(record, FailureRecord)
        assert record.retryable is True
        assert "trim" in record.display_message.lower()
        assert record.snapshot_id == made.books[0].snapshot.snapshot_id
    assert not any(t.staged.exists() for t in made.books[0].tracks), (
        "no invalid or zero-length output was manufactured")
    assert result.result.state is JobState.COMPLETED_WITH_FAILURES


# --------------------------------------------------------------------------- #
# The metadata whitelist
# --------------------------------------------------------------------------- #


def test_the_output_carries_exactly_the_intended_frames_and_none_of_the_junk(sources, reserve):
    made, entry = one_book_plan(
        sources, reserve, names=("01 One.mp3", "02 Two.mp3"),
        artist="New Artist", album_artist="New Narrator", album="New Album",
        chapter_titles="First\nSecond")
    proc.write_id3_run(made)
    for track, expected_title, number in zip(made.books[0].tracks, ("First", "Second"), (1, 2)):
        out = track.published
        assert set(frames(out)) == {"TIT2", "TPE1", "TPE2", "TALB", "TRCK"}
        text = texts(out)
        assert text["TIT2"] == expected_title
        assert text["TPE1"] == "New Artist"
        assert text["TPE2"] == "New Narrator"
        assert text["TALB"] == "New Album"
        assert text["TRCK"] == str(number), "an ordinary integer, not display-padded"
        assert set(frames(out)) <= WHITELIST
        for junk in ("TYER", "TCON", "TCOM", "COMM", "TXXX", "APIC"):
            assert junk not in frames(out), junk


def test_blank_frozen_scalars_are_absent_not_inherited_from_the_source(sources, reserve):
    made, entry = one_book_plan(sources, reserve, artist="", album_artist="", album="")
    proc.write_id3_run(made)
    out = made.books[0].tracks[0].published
    present = set(frames(out))
    assert "TPE1" not in present and "TPE2" not in present and "TALB" not in present
    assert texts(out)["TIT2"] == "Old Title", "the source Title seeds the track Title only"
    assert "Old Artist" not in str(texts(out).values())


def test_track_number_is_written_when_auto_number_is_on_and_omitted_when_off(sources, reserve):
    on, _ = one_book_plan(sources, reserve, names=("a.mp3", "b.mp3"), start_number="7")
    proc.write_id3_run(on)
    assert [texts(t.published)["TRCK"] for t in on.books[0].tracks] == ["7", "8"]
    off, _ = one_book_plan(sources, reserve, names=("a.mp3",), auto_number=False, title="")
    proc.write_id3_run(off)
    assert "TRCK" not in frames(off.books[0].tracks[0].published)
    assert off.books[0].tracks[0].published.name == "a.mp3"


def test_filenames_and_titles_are_the_frozen_plans(sources, reserve):
    made, entry = one_book_plan(sources, reserve, names=("03 Chapter 741_ Home Again.mp3",),
                                chapter_titles="", title="")
    proc.write_id3_run(made)
    track = made.books[0].tracks[0]
    assert track.published.name == "01 Chapter 741_ Home Again.mp3"
    assert texts(track.published)["TIT2"] == "Chapter 741: Home Again"
    assert track.published == made.books[0].published_dir / track.filename


def test_a_selected_png_and_jpg_are_embedded_and_old_art_never_survives(sources, reserve, tmp_path):
    cover = png(tmp_path / "cover.png")
    made, entry = one_book_plan(sources, reserve, names=("01.mp3", "02.mp3"),
                                artwork=str(cover))
    proc.write_id3_run(made)
    for track in made.books[0].tracks:
        apic = [f for k, f in frames(track.published).items() if k == "APIC"]
        assert len(apic) == 1
        assert apic[0].mime == "image/png" and int(apic[0].type) == 3
        assert apic[0].data == cover.read_bytes()
    jpeg = jpg(tmp_path / "cover.jpg")
    made, entry = one_book_plan(sources, reserve, artwork=str(jpeg))
    proc.write_id3_run(made)
    apic, = [f for k, f in frames(made.books[0].tracks[0].published).items() if k == "APIC"]
    assert apic.mime == "image/jpeg" and apic.data == jpeg.read_bytes()


def test_no_selected_artwork_means_no_apic_even_when_the_source_had_one(sources, reserve):
    made, entry = one_book_plan(sources, reserve)
    proc.write_id3_run(made)
    assert "APIC" not in frames(made.books[0].tracks[0].published)


def test_a_shared_artwork_reaches_every_book_through_the_frozen_plan(sources, reserve, tmp_path):
    cover = png(tmp_path / "shared.png")
    a = book([imported(sources, "A", "1.mp3")], artwork=str(jpg(tmp_path / "book.jpg")))
    b = book([imported(sources, "B", "1.mp3")])
    shared = SharedMetadata(wf.SHARED_FIELDS, {"artwork": str(cover)})
    made = plan(workspace(a, b, shared=shared), observe(a, b), reserve)
    proc.write_id3_run(made)
    for entry in made.books:
        apic, = [f for k, f in frames(entry.tracks[0].published).items() if k == "APIC"]
        assert apic.data == cover.read_bytes()


def test_an_undecodable_frozen_artwork_is_a_book_level_fatal_failure(sources, reserve, tmp_path):
    bad = tmp_path / "bad.png"
    bad.write_bytes(b"not an image")
    made, entry = one_book_plan(sources, reserve, artwork=str(bad))
    report = proc.write_id3_run(made)
    result = report.books[0].result
    assert result.state is JobState.FAILED
    fatal = tuple(result.failures.fatal)
    assert len(fatal) == 1
    assert fatal[0].item_id is None, "no fake occurrence id"
    assert fatal[0].retryable is False and "Artwork" in fatal[0].display_message
    assert result.has_retryable is False
    assert not made.books[0].published_dir.exists()


# --------------------------------------------------------------------------- #
# Book atomicity across Books
# --------------------------------------------------------------------------- #


def test_a_book_publishes_only_after_every_track_succeeds(sources, reserve, monkeypatch):
    made, entry = one_book_plan(sources, reserve, names=("01.mp3", "02.mp3", "03.mp3"), title="")
    seen: list[str] = []
    real = mp.publish_book

    def spy(book_plan):
        seen.append("publish")
        for path in book_plan.staged_outputs:
            assert path.is_file(), "every track is staged before publication"
        assert not book_plan.published_dir.exists()
        return real(book_plan)

    monkeypatch.setattr(proc.mp3_plan, "publish_book", spy)
    report = proc.write_id3_run(made)
    assert seen == ["publish"]
    assert report.books[0].succeeded
    assert sorted(p.name for p in made.books[0].published_dir.iterdir()) == [
        "01 01.mp3", "02 02.mp3", "03 03.mp3"]
    assert not made.books[0].staging_dir.exists() or not any(made.books[0].staging_dir.iterdir())


def test_a_fails_b_fails_c_succeeds_leaves_a_and_c_published_and_b_private(sources, reserve):
    a = book([imported(sources, "A", "1.mp3"), imported(sources, "A", "2.mp3")], album="A")
    bad = imported(sources, "B", "2.mp3", junk=False)
    bad.path.write_bytes(b"this is not an mp3 at all")
    b = book([imported(sources, "B", "1.mp3"), bad, imported(sources, "B", "3.mp3")], album="B")
    c = book([imported(sources, "C", "1.mp3")], album="C")
    made = plan(workspace(a, b, c), observe(a, b, c), reserve)
    report = proc.write_id3_run(made)

    ra, rb, rc = report.books
    assert ra.succeeded and rc.succeeded and not rb.succeeded
    assert made.books[0].published_dir.is_dir() and made.books[2].published_dir.is_dir()
    assert not made.books[1].published_dir.exists(), "B publishes nothing"
    assert [r.result.state for r in report.books] == [
        JobState.SUCCEEDED, JobState.COMPLETED_WITH_FAILURES, JobState.SUCCEEDED]

    # B's failure names the real occurrence; the other two staged pieces survive.
    record, = rb.result.failures.records
    assert record.item_id == bad.occurrence_id
    assert record.retryable is True
    assert rb.result.retryable_ids == (bad.occurrence_id,)
    survivors = [t for t in made.books[1].tracks if t.occurrence_id != bad.occurrence_id]
    assert all(t.staged.is_file() for t in survivors), "kept for the exact failed-item retry"
    assert not made.books[1].track_for(bad.occurrence_id).staged.exists()
    assert set(rb.result.completed_ids) == {t.occurrence_id for t in survivors}
    assert rb.staged_ok == tuple(t.occurrence_id for t in survivors)
    # The retry request Plan 7 derives is the failed subset against the same snapshot.
    request = rb.result.retry()
    assert request.item_ids == (bad.occurrence_id,)
    assert request.snapshot is made.books[1].snapshot
    assert report.failed_book_ids == (b.book_id,)


def test_every_source_hash_is_unchanged_after_a_whole_run(sources, reserve, tmp_path):
    a = book([imported(sources, "A", "1.mp3"), imported(sources, "A", "2.mp3")],
             time_delta="0.5", artwork=str(png(tmp_path / "c.png")))
    b = book([imported(sources, "B", "1.mp3", seconds=2.0)], time_delta="-0.5")
    made = plan(workspace(a, b), observe(a, b), reserve)
    before = {f.path: sha(f.path) for e in (a, b) for f in e.files.files}
    proc.write_id3_run(made)
    assert {path: sha(path) for path in before} == before
    assert sha(tmp_path / "c.png") == sha(tmp_path / "c.png")


def test_live_edits_after_capture_cannot_reach_the_processing(sources, reserve):
    files = [imported(sources, "Book", "01.mp3")]
    entry = book(files, album="Frozen Album", artist="Frozen Artist")
    space = workspace(entry)
    made = plan(space, observe(entry), reserve)
    # The workspace moves on; the plan is what runs.
    edited = wf.set_book_field(space, "album", "Live Album").workspace
    edited = wf.set_book_field(edited, "artist", "Live Artist").workspace
    edited = wf.set_book_field(edited, "chapter_titles", "Live Title").workspace
    assert edited.current.configuration["album"] == "Live Album"
    proc.write_id3_run(made)
    out = made.books[0].tracks[0].published
    assert texts(out)["TALB"] == "Frozen Album"
    assert texts(out)["TPE1"] == "Frozen Artist"
    assert texts(out)["TIT2"] == "Old Title"
    assert out.parent.name == "Frozen Album"


def test_the_report_is_plan3_run_results_per_book(sources, reserve):
    made, entry = one_book_plan(sources, reserve, names=("a.mp3", "b.mp3"))
    report = proc.write_id3_run(made)
    assert report.plan is made
    assert isinstance(report.books[0], BookReport)
    assert isinstance(report.books[0].result, RunResult)
    assert report.books[0].result.snapshot is made.books[0].snapshot
    assert set(report.books[0].result.completed_ids) == set(made.books[0].snapshot.item_ids)
    assert report.books[0].published == made.books[0].published_outputs
    assert report.failed_book_ids == ()
    assert [b.book_id for b in report.books] == [e.book_id for e in made.books]


def test_a_combine_plan_is_refused_here(sources, reserve):
    files = [imported(sources, "Book", "01.mp3")]
    entry = book(files)
    combine = mp.plan_run(
        workspace(entry), observe(entry), operation=mp.MP3Operation.COMBINE,
        reservation=reserve(), catalog=wf.MP3_CATALOG,
        import_options=ImportOptions.for_catalog(wf.MP3_CATALOG),
        effective_config=make_config(), id_factory=_IDS)
    with pytest.raises(proc.ProcessingError):
        proc.write_id3_run(combine)


def test_a_checkpoint_can_stop_the_run_between_tracks(sources, reserve):
    from shared.cancellation import ConversionCancelled

    made, entry = one_book_plan(sources, reserve, names=("a.mp3", "b.mp3", "c.mp3"))
    calls = {"n": 0}

    def checkpoint():
        calls["n"] += 1
        if calls["n"] == 2:
            raise ConversionCancelled("stop")

    with pytest.raises(ConversionCancelled):
        proc.write_id3_run(made, checkpoint=checkpoint)
    assert not made.books[0].published_dir.exists()


# --------------------------------------------------------------------------- #
# Validation of a staged track
# --------------------------------------------------------------------------- #


def test_validation_refuses_a_staged_file_that_lost_its_audio(sources, reserve):
    made, entry = one_book_plan(sources, reserve)
    track = made.books[0].tracks[0]
    mp.prepare_staging(made.books[0])
    track.staged.write_bytes(b"")
    with pytest.raises(proc.ProcessingError):
        proc.validate_staged_track(made.books[0], track, None, expected_duration=1.0)


def test_validation_refuses_the_wrong_frames(sources, reserve):
    made, entry = one_book_plan(sources, reserve, artist="A")
    track = made.books[0].tracks[0]
    mp.prepare_staging(made.books[0])
    tone(track.staged)
    junk_tag(track.staged)
    with pytest.raises(proc.ProcessingError):
        proc.validate_staged_track(made.books[0], track, None, expected_duration=1.0)


# --------------------------------------------------------------------------- #
# Boundaries
# --------------------------------------------------------------------------- #


def test_the_processing_module_owns_the_ffmpeg_helpers_and_the_panel_reexports_them():
    from mp3_tools import mp3_tool

    tree = ast.parse(MODULE.read_text(encoding="utf-8"))
    declared = {node.name for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)}
    for helper in ("run_ff", "ffmpeg_escape_listfile_path", "write_concat_listfile",
                   "ffprobe_duration_seconds", "seconds_to_hms", "concat_mp3s_fast",
                   "normalize_to_wav", "make_silence_wav", "concat_wavs_to_mp3",
                   "add_silence_to_mp3", "trim_from_end_mp3", "save_error_log",
                   "ensure_ffmpeg_available", "write_id3_run", "write_id3_book",
                   "validate_staged_track"):
        assert helper in declared, helper
    for name in ("run_ff", "write_concat_listfile", "seconds_to_hms", "save_error_log",
                 "add_silence_to_mp3", "trim_from_end_mp3", "ensure_ffmpeg_available"):
        assert getattr(mp3_tool, name) is getattr(proc, name), name


def test_the_processing_module_reaches_no_tk_controller_or_second_planner():
    tree = ast.parse(MODULE.read_text(encoding="utf-8"))
    modules = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules |= {alias.name for alias in node.names}
        elif isinstance(node, ast.ImportFrom):
            modules.add(node.module or "")
            modules |= {f"{node.module}.{alias.name}" for alias in node.names}
    for banned in ("tkinter", "threading", "queue", "shutil", "shared.job_ui",
                   "shared.ui_theme", "shared.import_coordination", "mp3_tools.mp3_tool",
                   "shared.job_control.JobController"):
        assert banned not in modules, banned
    declared = {node.name for node in ast.walk(tree)
                if isinstance(node, (ast.FunctionDef, ast.ClassDef))}
    for owned_elsewhere in ("plan_run", "track_filename", "book_folder_name",
                            "publish_book", "discard_staging", "load_artwork",
                            "apply_artwork", "DestinationPlanner", "JobController",
                            "RetryRequest", "retry_failed_books", "sanitize_component"):
        assert owned_elsewhere not in declared, owned_elsewhere
    called = {node.func.attr for node in ast.walk(tree)
              if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)}
    called |= {node.func.id for node in ast.walk(tree)
               if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)}
    for reused in ("prepare_staging", "publish_book", "artwork_for", "apply_artwork",
                   "settle"):
        assert reused in called, reused
    for combine_only in ("concat_mp3s_fast", "concat_wavs_to_mp3", "normalize_to_wav",
                         "make_silence_wav"):
        write = next(node for node in ast.walk(tree)
                     if isinstance(node, ast.FunctionDef) and node.name == "write_id3_book")
        inner = {n.func.id for n in ast.walk(write)
                 if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)}
        assert combine_only not in inner, f"Combine is Phase 8's: {combine_only}"
