"""The MP3 artwork / APIC service — v0.6.3 focused MP3 plan, Phase 6.

``mp3_tools/mp3_artwork.py`` is the one place the MP3 Tool turns a selected
image into what an ID3 tag carries. JPG/JPEG and PNG are embedded as the
source's own bytes; HEIC/HEIF is decoded through the shared capability path and
converted to PNG **in memory** for the tag only. Nothing here resizes, crops or
rewrites a source, and nothing writes an MP3 — the Write ID3 / Combine pipelines
apply the frame later, from the frozen ``BookPlan.artwork`` value.

Fixtures are small real images generated by Pillow under ``tmp_path``. HEIC
tests are gated on the shared capability probe, exactly as the chooser is.
"""

from __future__ import annotations

import ast
import hashlib
import io
from pathlib import Path, PurePath

import pytest
from PIL import Image

from shared import image_capabilities

from mp3_tools import mp3_artwork as art
from mp3_tools import mp3_plan as mp
from mp3_tools.mp3_artwork import Artwork, ArtworkError

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIVERSAL = REPO_ROOT / "scripts" / "Universal"
MODULE = UNIVERSAL / "mp3_tools" / "mp3_artwork.py"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def png(path: Path, size=(24, 16)) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (200, 30, 30)).save(path, format="PNG")
    return path


def jpg(path: Path, size=(32, 20)) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (30, 200, 30)).save(path, format="JPEG", quality=90)
    return path


def heic(path: Path, size=(40, 28)) -> Path:
    capability = image_capabilities.heif_capability()
    if not capability.decode:
        pytest.skip(f"this machine cannot decode HEIC/HEIF: {capability.detail}")
    if not capability.encode:
        pytest.skip(f"this machine cannot write a HEIC fixture: {capability.detail}")
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (30, 30, 200)).save(path, format=image_capabilities.HEIF_FORMAT)
    return path


def listing(root: Path) -> set[str]:
    return {p.relative_to(root).as_posix() for p in root.rglob("*")}


# --------------------------------------------------------------------------- #
# The chooser filter is the shared probe's
# --------------------------------------------------------------------------- #


def test_the_chooser_filter_derives_from_the_shared_capability():
    types = art.artwork_filetypes()
    patterns = types[0][1].split()
    assert patterns == [f"*{s}" for s in image_capabilities.decodable_suffixes()]
    assert types[-1] == ("All files", "*.*")


def test_the_service_declares_no_capability_list_of_its_own():
    tree = ast.parse(MODULE.read_text(encoding="utf-8"))
    literals = {node.value for node in ast.walk(tree)
                if isinstance(node, ast.Constant) and isinstance(node.value, str)}
    for suffix in (".heic", ".heif", ".jpg", ".jpeg", ".png"):
        assert suffix not in literals, f"{suffix} is the shared probe's to know"
    modules = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules |= {alias.name for alias in node.names}
        elif isinstance(node, ast.ImportFrom):
            modules.add(node.module or "")
            modules |= {f"{node.module}.{alias.name}" for alias in node.names}
    assert "pillow_heif" not in modules, "the optional import belongs to the shared probe"
    assert "shared.image_capabilities" in modules
    for banned in ("tkinter", "subprocess", "threading", "shutil", "shared.ffmpeg_utils",
                   "shared.job_ui", "shared.output_paths", "mp3_tools.mp3_tool"):
        assert banned not in modules, banned


# --------------------------------------------------------------------------- #
# Loading: JPG and PNG are the source bytes; HEIC is an in-memory PNG
# --------------------------------------------------------------------------- #


def test_a_jpeg_is_embedded_as_its_own_bytes(tmp_path):
    source = jpg(tmp_path / "cover.jpg")
    before = sha(source)
    loaded = art.load_artwork(source)
    assert isinstance(loaded, Artwork)
    assert loaded.mime == "image/jpeg"
    assert loaded.data == source.read_bytes(), "no re-encode, no resize"
    assert (loaded.width, loaded.height) == (32, 20)
    assert loaded.converted is False
    assert loaded.source == source
    assert sha(source) == before


def test_a_jpeg_with_the_other_spelling_is_still_jpeg(tmp_path):
    source = jpg(tmp_path / "cover.JPEG")
    assert art.load_artwork(source).mime == "image/jpeg"


def test_a_png_is_embedded_as_its_own_bytes(tmp_path):
    source = png(tmp_path / "cover.png")
    before = sha(source)
    loaded = art.load_artwork(source)
    assert loaded.mime == "image/png"
    assert loaded.data == source.read_bytes()
    assert (loaded.width, loaded.height) == (24, 16)
    assert loaded.converted is False
    assert sha(source) == before


def test_a_heic_becomes_an_in_memory_png_of_the_same_size(tmp_path):
    source = heic(tmp_path / "cover.heic", size=(40, 28))
    before = sha(source)
    snapshot = listing(tmp_path)
    loaded = art.load_artwork(source)
    assert loaded.mime == "image/png"
    assert loaded.converted is True
    assert loaded.data[:8] == b"\x89PNG\r\n\x1a\n"
    with Image.open(io.BytesIO(loaded.data)) as decoded:
        assert decoded.format == "PNG"
        assert decoded.size == (40, 28)
    assert sha(source) == before, "the source is never touched"
    assert listing(tmp_path) == snapshot, "no converted file appears anywhere"


def test_a_heic_is_refused_when_the_machine_cannot_decode_it(tmp_path, monkeypatch):
    source = tmp_path / "cover.heic"
    source.write_bytes(b"not really")
    monkeypatch.setattr(image_capabilities, "decodable_suffixes",
                        lambda: image_capabilities.BASELINE_SUFFIXES)
    with pytest.raises(ArtworkError) as refused:
        art.load_artwork(source)
    assert "HEIC" in str(refused.value) or ".heic" in str(refused.value)


def test_the_capability_probe_is_asked_before_a_heic_is_opened(tmp_path, monkeypatch):
    source = heic(tmp_path / "cover.heic")
    asked: list[str] = []
    real = image_capabilities.heif_capability

    def spy(**kwargs):
        asked.append("probe")
        return real(**kwargs)

    monkeypatch.setattr(image_capabilities, "heif_capability", spy)
    art.load_artwork(source)
    assert asked, "registration goes through the shared probe, never a local import"


@pytest.mark.parametrize("name,payload", [
    ("garbage.png", b"this is not a png"),
    ("garbage.jpg", b"\xff\xd8\xff nope"),
    ("empty.png", b""),
])
def test_an_undecodable_image_fails_visibly(tmp_path, name, payload):
    source = tmp_path / name
    source.write_bytes(payload)
    with pytest.raises(ArtworkError):
        art.load_artwork(source)


def test_a_mislabelled_image_is_refused_rather_than_mistagged(tmp_path):
    """A PNG saved as ``.jpg`` would be embedded with the wrong MIME; refuse it."""
    disguised = png(tmp_path / "actually.png")
    renamed = tmp_path / "actually.jpg"
    disguised.rename(renamed)
    with pytest.raises(ArtworkError):
        art.load_artwork(renamed)


def test_an_unsupported_suffix_or_missing_file_is_an_artwork_error(tmp_path):
    (tmp_path / "cover.gif").write_bytes(b"GIF89a")
    with pytest.raises(ArtworkError):
        art.load_artwork(tmp_path / "cover.gif")
    with pytest.raises(ArtworkError):
        art.load_artwork(tmp_path / "missing.png")
    with pytest.raises(ArtworkError):
        art.load_artwork("")


def test_loading_leaves_no_temporary_file_behind(tmp_path):
    jpg(tmp_path / "a.jpg")
    png(tmp_path / "b.png")
    before = listing(tmp_path)
    art.load_artwork(tmp_path / "a.jpg")
    art.load_artwork(tmp_path / "b.png")
    assert listing(tmp_path) == before


# --------------------------------------------------------------------------- #
# APIC
# --------------------------------------------------------------------------- #


def apic_frames(tags):
    return [frame for frame in tags.values() if frame.FrameID == "APIC"]


def test_the_frame_is_one_front_cover_with_the_exact_bytes(tmp_path):
    from mutagen.id3 import ID3, PictureType

    source = png(tmp_path / "cover.png")
    loaded = art.load_artwork(source)
    tags = ID3()
    art.apply_artwork(tags, loaded)
    frames = apic_frames(tags)
    assert len(frames) == 1
    frame = frames[0]
    assert frame.type == PictureType.COVER_FRONT
    assert int(frame.type) == 3
    assert frame.mime == "image/png"
    assert frame.data == source.read_bytes()
    with Image.open(io.BytesIO(frame.data)) as embedded:
        assert embedded.size == (24, 16)


def test_old_artwork_never_survives_the_intended_state(tmp_path):
    from mutagen.id3 import APIC, ID3

    tags = ID3()
    tags.add(APIC(encoding=3, mime="image/jpeg", type=3, desc="old", data=b"old front"))
    tags.add(APIC(encoding=3, mime="image/jpeg", type=4, desc="back", data=b"old back"))
    assert len(apic_frames(tags)) == 2

    # Intended: a new front cover -> exactly that one, nothing old.
    loaded = art.load_artwork(jpg(tmp_path / "new.jpg"))
    art.apply_artwork(tags, loaded)
    frames = apic_frames(tags)
    assert len(frames) == 1 and frames[0].data == loaded.data

    # Intended: no artwork -> no APIC at all.
    art.apply_artwork(tags, None)
    assert apic_frames(tags) == []


def test_no_artwork_means_no_apic_on_a_fresh_tag():
    from mutagen.id3 import ID3

    tags = ID3()
    art.apply_artwork(tags, None)
    assert apic_frames(tags) == []


def test_applying_twice_still_leaves_exactly_one_frame(tmp_path):
    from mutagen.id3 import ID3

    tags = ID3()
    first = art.load_artwork(png(tmp_path / "a.png"))
    second = art.load_artwork(jpg(tmp_path / "b.jpg"))
    art.apply_artwork(tags, first)
    art.apply_artwork(tags, second)
    frames = apic_frames(tags)
    assert len(frames) == 1
    assert frames[0].mime == "image/jpeg" and frames[0].data == second.data


def test_the_frame_round_trips_through_a_real_id3_write(tmp_path):
    """The one place a file is written here, and it is a test-owned stub."""
    from mutagen.id3 import ID3

    source = jpg(tmp_path / "cover.jpg")
    stub = tmp_path / "track.mp3"
    stub.write_bytes(b"\x00" * 64)
    tags = ID3()
    art.apply_artwork(tags, art.load_artwork(source))
    tags.save(stub)
    read_back = apic_frames(ID3(stub))
    assert len(read_back) == 1
    assert read_back[0].data == source.read_bytes()
    assert read_back[0].mime == "image/jpeg" and int(read_back[0].type) == 3


def test_a_heic_frame_is_png_bytes_with_preserved_dimensions(tmp_path):
    from mutagen.id3 import ID3

    source = heic(tmp_path / "cover.heic", size=(40, 28))
    tags = ID3()
    art.apply_artwork(tags, art.load_artwork(source))
    frame, = apic_frames(tags)
    assert frame.mime == "image/png"
    with Image.open(io.BytesIO(frame.data)) as embedded:
        assert embedded.format == "PNG" and embedded.size == (40, 28)
    assert not (tmp_path / "cover.png").exists()


def test_apply_refuses_anything_but_an_artwork_or_none(tmp_path):
    from mutagen.id3 import ID3

    for wrong in ("cover.png", b"bytes", 7, object()):
        with pytest.raises(ArtworkError):
            art.apply_artwork(ID3(), wrong)


# --------------------------------------------------------------------------- #
# Preview: in memory, never the source, never the tag
# --------------------------------------------------------------------------- #


def test_preview_is_an_in_memory_thumbnail_that_changes_nothing(tmp_path):
    source = jpg(tmp_path / "big.jpg", size=(300, 200))
    before = sha(source)
    snapshot = listing(tmp_path)
    preview = art.preview_image(source, (56, 56))
    assert isinstance(preview, Image.Image)
    assert max(preview.size) <= 56
    assert preview.size == (56, 37)
    assert sha(source) == before
    assert listing(tmp_path) == snapshot
    loaded = art.load_artwork(source)
    assert (loaded.width, loaded.height) == (300, 200), "the tag gets the full image"
    assert loaded.data == source.read_bytes()


def test_preview_of_a_heic_uses_the_same_capability_gate(tmp_path):
    source = heic(tmp_path / "cover.heic", size=(90, 60))
    preview = art.preview_image(source, (30, 30))
    assert preview.size == (30, 20)


def test_preview_of_an_undecodable_file_raises_the_same_error(tmp_path):
    bad = tmp_path / "bad.png"
    bad.write_bytes(b"nope")
    with pytest.raises(ArtworkError):
        art.preview_image(bad, (56, 56))


# --------------------------------------------------------------------------- #
# Frozen-plan compatibility
# --------------------------------------------------------------------------- #


def test_artwork_is_loaded_from_the_frozen_book_plan_value(tmp_path):
    from shared import book_workspace, output_paths
    from shared.importing import (IdFactory, ImportOptions, ImportedFile,
                                  ImportedFileSnapshot, ImportRoot, Revision)
    from mp3_tools import mp3_workflow as wf
    from test_importing import make_config

    ids = IdFactory("art-")
    source = tmp_path / "Sources" / "Book" / "1.mp3"
    source.parent.mkdir(parents=True)
    source.write_bytes(b"x")
    cover = png(tmp_path / "cover.png")
    entry = ImportedFile(ids.next_id("occurrence"), source,
                         ImportRoot("r", tmp_path / "Sources", 0), PurePath("Book/1.mp3"),
                         "mp3", "id-1")
    book = book_workspace.BookJob(
        book_id=book_workspace.new_book_id(ids), configuration={"artwork": str(cover)},
        files=ImportedFileSnapshot(Revision(1), (entry,)))
    space = book_workspace.WorkspaceSnapshot(
        books=(book,), current_book_id=book.book_id, shared=wf.new_shared_metadata())
    run = tmp_path / "Outputs" / "MP3-Tool-1"
    run.mkdir(parents=True)
    reservation = output_paths.RunReservation(
        tool_key="mp3_tool", base_directory=tmp_path / "Outputs",
        tool_directory=tmp_path / "Outputs", run_directory=run, run_number=1)
    store = wf.ObservationStore().with_observations(
        wf.observe_files((entry,), reader=lambda p: wf.SourceTags()))
    plan = mp.plan_run(space, store, operation=mp.MP3Operation.WRITE_ID3,
                       reservation=reservation, catalog=wf.MP3_CATALOG,
                       import_options=ImportOptions.for_catalog(wf.MP3_CATALOG),
                       effective_config=make_config(), id_factory=ids)
    frozen = plan.books[0]
    assert frozen.artwork == cover
    loaded = art.artwork_for(frozen)
    assert loaded is not None and loaded.data == cover.read_bytes()

    # The plan value is what counts: replacing the file afterwards is a
    # different image, and a later load honestly reports the *current* bytes
    # of the frozen path -- the panel's live widgets are never consulted.
    none_plan = mp.BookPlan(**{**{f: getattr(frozen, f) for f in frozen.__dataclass_fields__},
                               "artwork": None})
    assert art.artwork_for(none_plan) is None


def test_a_frozen_path_that_no_longer_decodes_is_a_visible_error(tmp_path):
    from types import SimpleNamespace

    with pytest.raises(ArtworkError):
        art.artwork_for(SimpleNamespace(artwork=tmp_path / "vanished.png"))
