"""The shared M4B artwork service — v0.6.4 Phase 1.

``mp3_tools/m4b_artwork.py`` is the one place both M4B tools (Maker and
Metadata Editor) turn a selected image into what an MP4 container's ``covr``
atom carries. The rules are the v0.6.4 plan's (sections 4.6, 5.11, 6.12,
Phase 1):

- which files may be chosen is the shared capability probe's answer, never a
  list of this module's own — JPG/JPEG and PNG always, HEIC/HEIF only where
  ``shared.image_capabilities`` says the machine decodes it;
- JPG/JPEG and PNG are validated by decoding and embedded as the source's own
  bytes with the matching MP4 cover format; a file whose content does not match
  its name is refused rather than mis-tagged;
- HEIC/HEIF is converted **in memory** to PNG, pixel dimensions preserved, and
  no converted file is written anywhere;
- the selected source is read-only: its hash never changes and no sidecar
  appears beside it;
- embedding touches only the ``covr`` atom of the target container — the audio
  stream is not re-encoded.

Decoding, thumbnailing and the chooser filter are the same shared path the MP3
Tool already proved (``mp3_artwork``); what is M4B-specific here is only the
container representation. Nothing here reaches Tk, a thread, a subprocess or a
panel. Fixtures are tiny real images generated by Pillow under ``tmp_path``;
the one real container is a six-second AAC ``.m4a`` built by the project's own
FFmpeg, which is a required tool rather than a reason to skip.
"""

from __future__ import annotations

import ast
import hashlib
import io
import subprocess
from pathlib import Path

import pytest
from PIL import Image

from shared import ffmpeg_utils, image_capabilities

from mp3_tools import m4b_artwork as art
from mp3_tools import mp3_artwork
from mp3_tools.m4b_artwork import ArtworkError, M4BCover

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIVERSAL = REPO_ROOT / "scripts" / "Universal"
MODULE = UNIVERSAL / "mp3_tools" / "m4b_artwork.py"


# --------------------------------------------------------------------------- #
# Fixtures
# --------------------------------------------------------------------------- #


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def png(path: Path, size=(24, 16)) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (200, 30, 30)).save(path, format="PNG")
    return path


def jpg(path: Path, size=(32, 20)) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (30, 200, 30)).save(path, format="JPEG", quality=90)
    return path


def heic(path: Path, size=(40, 28)) -> Path:
    capability = image_capabilities.heif_capability()
    if not capability.decode:
        pytest.skip(f"this machine cannot decode HEIC/HEIF: {capability.detail}")
    if not capability.encode:
        pytest.skip(f"this machine cannot write a HEIC fixture: {capability.detail}")
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size, (30, 30, 200)).save(path, format=image_capabilities.HEIF_FORMAT)
    return path


def listing(root: Path) -> set[str]:
    return {p.relative_to(root).as_posix() for p in root.rglob("*")}


def require_ffmpeg() -> str:
    """FFmpeg is a required tool: an unresolvable binary is a failure, not a skip."""
    if not ffmpeg_utils.have_ffmpeg():
        pytest.fail("ffmpeg/ffprobe could not be resolved, so the real-container "
                    f"cases cannot run: ffmpeg_path()={ffmpeg_utils.ffmpeg_path()!r}")
    return ffmpeg_utils.ffmpeg_cmd()


def _ff(*args) -> bytes:
    out = subprocess.run([ffmpeg_utils.ffmpeg_cmd(), "-hide_banner", "-v", "error", "-y", *args],
                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert out.returncode == 0, out.stdout.decode("utf-8", "replace")[-800:]
    return out.stdout


def audio_digest(path: Path) -> str:
    """MD5 of the packed audio stream, copied without re-encoding.

    Two files whose audio was not touched give the same digest; a re-encode
    cannot.
    """
    out = _ff("-i", str(path), "-map", "0:a", "-c", "copy", "-f", "md5", "-")
    return out.decode("ascii", "replace").strip()


@pytest.fixture(scope="module")
def m4a(tmp_path_factory) -> Path:
    require_ffmpeg()
    work = tmp_path_factory.mktemp("m4b_artwork")
    target = work / "book.m4a"
    _ff("-f", "lavfi", "-i", "sine=frequency=440:duration=6", "-c:a", "aac",
        "-b:a", "64k", str(target))
    return target


def covr_of(path: Path) -> list:
    from mutagen.mp4 import MP4
    tags = MP4(str(path)).tags
    return list(tags.get("covr", [])) if tags else []


# --------------------------------------------------------------------------- #
# One capability authority, one decode path, nothing reinvented
# --------------------------------------------------------------------------- #


def test_the_chooser_filter_is_the_shared_probes():
    types = art.artwork_filetypes()
    patterns = types[0][1].split()
    assert patterns == [f"*{s}" for s in image_capabilities.decodable_suffixes()]
    assert types == mp3_artwork.artwork_filetypes(), "one chooser filter for every tool"


def test_the_service_keeps_no_capability_list_and_reinvents_no_decoder():
    tree = ast.parse(MODULE.read_text(encoding="utf-8"))
    literals = {node.value for node in ast.walk(tree)
                if isinstance(node, ast.Constant) and isinstance(node.value, str)}
    for suffix in (".heic", ".heif", ".jpg", ".jpeg", ".png", "image/png", "image/jpeg"):
        assert suffix not in literals, f"{suffix!r} belongs to a registry, not here"
    modules = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules |= {alias.name for alias in node.names}
        elif isinstance(node, ast.ImportFrom):
            modules.add(node.module or "")
            modules |= {f"{node.module}.{alias.name}" for alias in node.names}
    assert "pillow_heif" not in modules, "the optional import belongs to the shared probe"
    assert "mp3_tools.mp3_artwork" in modules, "decoding is the proved shared path"
    for banned in ("tkinter", "subprocess", "threading", "shutil", "queue",
                   "shared.ffmpeg_utils", "shared.job_ui", "shared.job_control",
                   "shared.output_paths", "shared.importing", "shared.book_workspace",
                   "shared.metadata", "mp3_tools.mp3_tool", "mp3_tools.mp3_plan",
                   "mp3_tools.mp3_processing", "mp3_tools.mp3_workflow",
                   "mp3_tools.m4b_maker", "mp3_tools.m4b_metadata_editor"):
        assert banned not in modules, banned
    defined = {node.name for node in ast.walk(tree)
               if isinstance(node, (ast.FunctionDef, ast.ClassDef))}
    for reused in ("load_artwork", "preview_image", "_open", "_require_source",
                   "_format_for", "_mime_of", "artwork_filetypes"):
        assert reused not in defined, f"{reused} is mp3_artwork's; reuse it"
    calls = {node.func.attr for node in ast.walk(tree)
             if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)}
    for decoding in ("open", "load", "thumbnail", "convert", "read_bytes"):
        assert decoding not in calls, f"{decoding}() is the shared decode path's, not this module's"


def test_the_service_is_a_pure_module_with_the_expected_surface():
    assert set(art.__all__) >= {
        "ArtworkError", "M4BCover", "artwork_filetypes", "load_cover", "cover_for",
        "apply_cover", "embed_cover", "preview_image",
    }
    assert art.ArtworkError is mp3_artwork.ArtworkError, "one error type to catch"


# --------------------------------------------------------------------------- #
# Loading: JPG/PNG are the source bytes; HEIC is an in-memory PNG
# --------------------------------------------------------------------------- #


def test_a_jpeg_is_carried_as_its_own_bytes(tmp_path):
    from mutagen.mp4 import MP4Cover

    source = jpg(tmp_path / "cover.jpg", size=(32, 20))
    before = sha(source)
    cover = art.load_cover(source)
    assert isinstance(cover, M4BCover)
    assert cover.data == source.read_bytes()
    assert cover.image_format == MP4Cover.FORMAT_JPEG
    assert (cover.width, cover.height) == (32, 20)
    assert cover.converted is False
    assert cover.source == source
    assert sha(source) == before


def test_a_png_is_carried_as_its_own_bytes(tmp_path):
    from mutagen.mp4 import MP4Cover

    source = png(tmp_path / "cover.png", size=(24, 16))
    cover = art.load_cover(source)
    assert cover.data == source.read_bytes()
    assert cover.image_format == MP4Cover.FORMAT_PNG
    assert (cover.width, cover.height) == (24, 16)
    assert cover.converted is False


def test_a_heic_becomes_an_in_memory_png_cover_of_the_same_size(tmp_path):
    from mutagen.mp4 import MP4Cover

    source = heic(tmp_path / "cover.heic", size=(40, 28))
    before = sha(source)
    snapshot = listing(tmp_path)
    cover = art.load_cover(source)
    assert cover.image_format == MP4Cover.FORMAT_PNG
    assert cover.converted is True
    assert cover.data[:8] == b"\x89PNG\r\n\x1a\n"
    with Image.open(io.BytesIO(cover.data)) as decoded:
        assert decoded.format == "PNG"
        assert decoded.size == (40, 28)
    assert (cover.width, cover.height) == (40, 28)
    assert sha(source) == before, "the source is never touched"
    assert listing(tmp_path) == snapshot, "no converted sidecar appears anywhere"


def test_a_heic_is_refused_where_the_machine_cannot_decode_it(tmp_path, monkeypatch):
    source = tmp_path / "cover.heic"
    source.write_bytes(b"not really")
    monkeypatch.setattr(image_capabilities, "decodable_suffixes",
                        lambda: image_capabilities.BASELINE_SUFFIXES)
    with pytest.raises(ArtworkError) as refused:
        art.load_cover(source)
    assert "HEIC" in str(refused.value) or ".heic" in str(refused.value)
    assert listing(tmp_path) == {"cover.heic"}


def test_a_mislabelled_image_is_refused_rather_than_mistagged(tmp_path):
    real_png = png(tmp_path / "real.png")
    lying = tmp_path / "lying.jpg"
    lying.write_bytes(real_png.read_bytes())
    before = sha(lying)
    with pytest.raises(ArtworkError):
        art.load_cover(lying)
    assert sha(lying) == before


@pytest.mark.parametrize("name,payload", [
    ("empty.jpg", b""),
    ("garbage.png", b"\x00\x01\x02 not an image"),
    ("text.jpeg", b"hello"),
])
def test_an_undecodable_image_fails_visibly(tmp_path, name, payload):
    source = tmp_path / name
    source.write_bytes(payload)
    with pytest.raises(ArtworkError):
        art.load_cover(source)


def test_an_unsupported_suffix_or_missing_file_is_an_artwork_error(tmp_path):
    (tmp_path / "cover.gif").write_bytes(b"GIF89a")
    with pytest.raises(ArtworkError):
        art.load_cover(tmp_path / "cover.gif")
    with pytest.raises(ArtworkError):
        art.load_cover(tmp_path / "missing.png")
    with pytest.raises(ArtworkError):
        art.load_cover("")
    with pytest.raises(ArtworkError):
        art.load_cover(None)


def test_loading_writes_nothing_anywhere_near_the_source(tmp_path):
    jpg(tmp_path / "a.jpg")
    png(tmp_path / "nested" / "b.png")
    before = listing(tmp_path)
    hashes = {p: sha(p) for p in tmp_path.rglob("*") if p.is_file()}
    art.load_cover(tmp_path / "a.jpg")
    art.load_cover(tmp_path / "nested" / "b.png")
    assert listing(tmp_path) == before
    assert {p: sha(p) for p in tmp_path.rglob("*") if p.is_file()} == hashes


def test_the_cover_is_immutable(tmp_path):
    cover = art.load_cover(png(tmp_path / "c.png"))
    with pytest.raises(Exception):
        cover.data = b""  # type: ignore[misc]


# --------------------------------------------------------------------------- #
# The frozen-plan seam
# --------------------------------------------------------------------------- #


def test_cover_for_reads_only_the_frozen_artwork_value(tmp_path):
    class Plan:
        def __init__(self, artwork):
            self.artwork = artwork
            self.title = "never read"

    source = png(tmp_path / "c.png")
    assert art.cover_for(Plan(None)) is None
    assert art.cover_for(Plan("")) is None
    assert art.cover_for(Plan("   ")) is None
    loaded = art.cover_for(Plan(str(source)))
    assert loaded is not None and loaded.data == source.read_bytes()
    with pytest.raises(ArtworkError):
        art.cover_for(Plan(str(tmp_path / "gone.png")))


# --------------------------------------------------------------------------- #
# The container: exactly one covr, or none — and the audio is never re-encoded
# --------------------------------------------------------------------------- #


def test_apply_cover_sets_exactly_one_covr_with_the_exact_bytes(tmp_path):
    from mutagen.mp4 import MP4Cover, MP4Tags

    tags = MP4Tags()
    tags["covr"] = [MP4Cover(b"old", imageformat=MP4Cover.FORMAT_JPEG),
                    MP4Cover(b"older", imageformat=MP4Cover.FORMAT_JPEG)]
    tags["\xa9nam"] = ["Kept"]
    cover = art.load_cover(png(tmp_path / "c.png"))
    art.apply_cover(tags, cover)
    assert len(tags["covr"]) == 1
    assert bytes(tags["covr"][0]) == cover.data
    assert tags["covr"][0].imageformat == MP4Cover.FORMAT_PNG
    assert tags["\xa9nam"] == ["Kept"], "unrelated atoms are not this function's"


def test_apply_cover_with_none_removes_the_artwork():
    from mutagen.mp4 import MP4Cover, MP4Tags

    tags = MP4Tags()
    tags["covr"] = [MP4Cover(b"old", imageformat=MP4Cover.FORMAT_JPEG)]
    art.apply_cover(tags, None)
    assert "covr" not in tags
    art.apply_cover(tags, None)
    assert "covr" not in tags


def test_apply_cover_refuses_anything_but_a_cover_or_none(tmp_path):
    from mutagen.mp4 import MP4Tags

    with pytest.raises(ArtworkError):
        art.apply_cover(MP4Tags(), str(png(tmp_path / "c.png")))
    with pytest.raises(ArtworkError):
        art.apply_cover(MP4Tags(), b"bytes")
    with pytest.raises(ArtworkError):
        art.apply_cover(MP4Tags(), mp3_artwork.load_artwork(png(tmp_path / "d.png")))


def test_embed_cover_writes_only_the_covr_atom_of_a_real_container(tmp_path, m4a):
    from mutagen.mp4 import MP4Cover

    import shutil
    staged = tmp_path / "staged.m4b"
    shutil.copy2(m4a, staged)
    source = jpg(tmp_path / "cover.jpg", size=(32, 20))
    source_before = sha(source)
    audio_before = audio_digest(staged)
    cover = art.load_cover(source)

    art.embed_cover(staged, cover)

    found = covr_of(staged)
    assert len(found) == 1
    assert bytes(found[0]) == source.read_bytes()
    assert found[0].imageformat == MP4Cover.FORMAT_JPEG
    assert audio_digest(staged) == audio_before, "the audio stream was re-encoded"
    assert sha(source) == source_before
    assert sha(m4a) != sha(staged) and covr_of(m4a) == [], "the original is untouched"


def test_embed_cover_replaces_and_then_removes(tmp_path, m4a):
    from mutagen.mp4 import MP4Cover

    import shutil
    staged = tmp_path / "staged.m4b"
    shutil.copy2(m4a, staged)
    art.embed_cover(staged, art.load_cover(jpg(tmp_path / "one.jpg")))
    art.embed_cover(staged, art.load_cover(png(tmp_path / "two.png")))
    found = covr_of(staged)
    assert len(found) == 1 and found[0].imageformat == MP4Cover.FORMAT_PNG
    audio_before = audio_digest(staged)
    art.embed_cover(staged, None)
    assert covr_of(staged) == []
    assert audio_digest(staged) == audio_before


def test_a_heic_cover_lands_in_the_container_as_png(tmp_path, m4a):
    from mutagen.mp4 import MP4Cover

    import shutil
    source = heic(tmp_path / "cover.heic", size=(40, 28))
    staged = tmp_path / "staged.m4b"
    shutil.copy2(m4a, staged)
    snapshot = listing(tmp_path)
    art.embed_cover(staged, art.load_cover(source))
    found = covr_of(staged)
    assert len(found) == 1 and found[0].imageformat == MP4Cover.FORMAT_PNG
    with Image.open(io.BytesIO(bytes(found[0]))) as decoded:
        assert decoded.size == (40, 28)
    assert listing(tmp_path) == snapshot, "no sidecar; only the staged copy changed"


def test_embed_cover_on_a_non_container_is_a_visible_error(tmp_path):
    not_mp4 = tmp_path / "not.m4b"
    not_mp4.write_bytes(b"definitely not an mp4")
    with pytest.raises(ArtworkError):
        art.embed_cover(not_mp4, art.load_cover(png(tmp_path / "c.png")))


# --------------------------------------------------------------------------- #
# Preview
# --------------------------------------------------------------------------- #


def test_preview_is_an_in_memory_thumbnail_that_changes_nothing(tmp_path):
    source = png(tmp_path / "big.png", size=(400, 300))
    before = sha(source)
    snapshot = listing(tmp_path)
    thumb = art.preview_image(source, (64, 64))
    assert max(thumb.size) <= 64
    assert sha(source) == before
    assert listing(tmp_path) == snapshot
    assert art.load_cover(source).data == source.read_bytes(), "preview scale never leaks"


def test_preview_of_an_undecodable_file_raises_the_same_error(tmp_path):
    bad = tmp_path / "bad.jpg"
    bad.write_bytes(b"nope")
    with pytest.raises(ArtworkError):
        art.preview_image(bad, (64, 64))
